clear;clc;
fprintf('[INFO] Starting compilation\n');

compile_dir = fullfile('.','compiled','fcd_maps2');
mkdir(compile_dir);

mcc('-m', 'run_fcd_maps.m','-C', '-v',...
    '-o', 'FCD_Maps_v0_1',...
    '-d', compile_dir,...
    '-R', '-logfile,output.txt',...
    '-R', '-startmsg,[INFO]Starting application, please wait...',...
    '-a', fullfile(spm('dir'),'Contents.txt'),...
    '-a', fullfile(spm('dir'),'tpm'),...
    '-a', fullfile(spm('dir'),'toolbox','Shoot'),...
    '-a', fullfile(spm('dir'),'toolbox','OldNorm'),...
    '-a', fullfile(get_path('cat12_dir'),'templates_MNI152NLin2009cAsym'),...
    '-a', fullfile(get_path("cat12_dir"),'Contents.txt'),...
    '-a', fullfile(pwd,'utils'));

%-r 'path/to/my_icon.ico'
%-Z 'autodetect'

fprintf('\n[INFO] Compilation done!\n');

%tengo que especificar que templates quiero de cat12